### ISSUE TITLE
Possible typo

### ISSUE THREAD

**Issue by kyriakos-georgiou** [janblechschmidt/PDEsByNNs#2]
Hello @janblechschmidt,

Thank you very much for providing your code. My question is regarding the boundary function:

def fun_u_b_0(t, x):
    n = x.shape[0]
    return tf.zeros((n,1), dtype=DTYPE)

Given that this results in the boundary condition across the values of t, should it not be n = t.shape[0]?

Thank you for your time!

**Comment by janblechschmidt** [comment]
Dear @kyriakos-georgiou,

thank you for pointing this out. Since both `t` and `x` are assumed to have the same number of rows, it actually doesn't matter in this case. If you, however, would split the function into two functions `u_b_up(t)` and `u_b_low(t)` which don't depend on `x`, then you would have to change this.

Best regards,
Jan

**Comment by kyriakos-georgiou** [comment]
Thank you very much for replying! 

Best,
Kyriakos
